---
abstract: 'Parse text markup into HTML'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  File::Spec::Functions: 0
  Module::Build: 0.30
  Test::More: 0.96
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Markup
provides:
  Text::Markup:
    file: lib/Text/Markup.pm
    version: 0.12
  Text::Markup::HTML:
    file: lib/Text/Markup/HTML.pm
    version: 0.12
  Text::Markup::Markdown:
    file: lib/Text/Markup/Markdown.pm
    version: 0.12
  Text::Markup::Mediawiki:
    file: lib/Text/Markup/Mediawiki.pm
    version: 0.12
  Text::Markup::Multimarkdown:
    file: lib/Text/Markup/Multimarkdown.pm
    version: 0.12
  Text::Markup::None:
    file: lib/Text/Markup/None.pm
    version: 0.12
  Text::Markup::Pod:
    file: lib/Text/Markup/Pod.pm
    version: 0.12
  Text::Markup::Textile:
    file: lib/Text/Markup/Textile.pm
    version: 0.12
  Text::Markup::Trac:
    file: lib/Text/Markup/Trac.pm
    version: 0.12
recommends:
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
requires:
  File::BOM: 0.14
  HTML::Entities: 0
  Pod::Simple::XHTML: 3.15
  Text::Markdown: 1.000004
  Text::MediawikiFormat: 1.0
  Text::MultiMarkdown: 1.000028
  Text::Textile: 2.10
  Text::Trac: 0.10
  perl: 5.008001
resources:
  bugtracker: http://github.com/theory/text-markup/issues/
  homepage: http://search.cpan.org/dist/Text-Markup/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/text-markup/tree/
version: 0.12
